repositories:
  - name: softwarefactory
    url: https://elkouhen.github.io/sf-charts/
    # url: ../../../charts/jenkins-impl

releases:

  - name: jenkins
    namespace: prod
    chart: softwarefactory/jenkins-impl
    values:
      - "./values.yaml"