repositories:
  - name: softwarefactory
    url: https://elkouhen.github.io/sf-charts/
    # url: ../../../charts/jenkins-impl

releases:

  - name: jenkins
    namespace: prod
    chart: softwarefactory/jenkins-impl
    values:
      - "./values.yaml"
      - namespace: prod
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
            kubernetes.io/tls-acme: "true"
          hosts:
            - jenkins.melkouhen.net
          secretName: jenkins-secret
          tls:
            - hosts:
              - jenkins.melkouhen.net
              secretName: jenkins-secret
        service:
          type: LoadBalancer